{
  "openapi": "3.0.3",
  "info": {
    "title": "Cashier API",
    "description": "API for cashier",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8000"
    }
  ],
  "paths": {
    "/api/cashiers": {
      "get": {
        "tags": [
          "Cashier"
        ],
        "summary": "Get all cashiers",
        "description": "Get all cashiers",
        "responses": {
          "200": {
            "description": "Success get all cashiers",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CashierListResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "description": "Invalid or missing token",
                    "value": {
                      "errors": {
                        "message": [
                          "Unauthorized"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Cashier"
        ],
        "summary": "Create cashier",
        "description": "Create cashier",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCashierRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create cashier",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CashierResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "examples": {
                  "Validation Error": {
                    "description": "Validation error",
                    "value": {
                      "errors": {
                        "name": [
                          "Name is required"
                        ],
                        "email": [
                          "Email is required"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "description": "Invalid or missing token",
                    "value": {
                      "errors": {
                        "message": [
                          "Unauthorized"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/cashiers/{id}": {
      "get": {
        "tags": [
          "Cashier"
        ],
        "summary": "Get cashier by id",
        "description": "Get cashier by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the cashier",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get cashier by id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CashierResponse"
                }
              }
            }
          },
          "404": {
            "description": "Cashier not found",
            "content": {
              "application/json": {
                "examples": {
                  "Cashier not found": {
                    "value": {
                      "errors": {
                        "message": [
                          "Cashier not found"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "description": "Invalid or missing token",
                    "value": {
                      "errors": {
                        "message": [
                          "Unauthorized"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Cashier"
        ],
        "summary": "Update cashier",
        "description": "Update cashier",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the cashier",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCashierRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update cashier",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CashierResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "examples": {
                  "Validation Error": {
                    "value": {
                      "errors": {
                        "name": [
                          "Name is required"
                        ],
                        "email": [
                          "Email is required"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "description": "Invalid or missing token",
                    "value": {
                      "errors": {
                        "message": [
                          "Unauthorized"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Cashier"
        ],
        "summary": "Delete cashier",
        "description": "Delete cashier",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the cashier",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete cashier",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string",
                      "example": "Cashier deleted successfully"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cashier not found",
            "content": {
              "application/json": {
                "examples": {
                  "Cashier not found": {
                    "value": {
                      "errors": {
                        "message": [
                          "Cashier not found"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "description": "Invalid or missing token",
                    "value": {
                      "errors": {
                        "message": [
                          "Unauthorized"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CashierListResponse": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Cashier"
            }
          }
        }
      },
      "CashierResponse": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Cashier"
          }
        }
      },
      "Cashier": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "example": "john.doe@example.com"
          },
          "total_sales": {
            "type": "number",
            "example": 100000
          }
        }
      },
      "CreateCashierRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "example": "john.doe@example.com"
          },
          "password": {
            "type": "string",
            "example": "password"
          }
        }
      },
      "UpdateCashierRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "example": "john.doe@example.com"
          },
          "password": {
            "type": "string",
            "example": "password"
          }
        }
      }
    }
  }
}